# Markdownlint configuration for Echo (Transcriber) project

# Default rule severity
default: true

# Rules to enable
MD001: true   # Heading levels should only increment by one
MD002: true   # First heading should be a top-level heading
MD003: true   # Heading style should be consistent (ATX-style)
MD004: true   # Unordered list style should be consistent (asterisks)
MD005: true   # List indentation should be consistent
MD007: true   # Unordered list indentation should be 2 spaces
MD009: true   # Trailing spaces should be removed
MD010: true   # Hard tabs should not be used
MD011: true   # Reversed link syntax should not be used
MD012: true   # Multiple consecutive blank lines should be reduced
MD013:        # Line length should be limited
  line_length: 120
  code_blocks: false
  tables: false
MD014: true   # Code block indentation should be consistent
MD018: true   # No space after hash on atx-style heading
MD019: true   # No multiple spaces after hash on atx-style heading
MD020: true   # No space inside headings
MD022: true   # Headings should end with appropriate punctuation
MD023: true   # Headings must start at column 1
MD024: true   # No duplicate heading levels
MD025: true   # Multiple top-level headings in the same document
MD026: true   # Trailing punctuation in heading should be removed
MD027: true   # Multiple consecutive blank lines after list item should be reduced
MD028: true   # Blank line after blockquote is required
MD029: true   # Ordered list item prefix should be consistent
MD030: true   # Spaces after list markers should be consistent
MD031: true   # Fenced code blocks should have blank lines before and after
MD032: true   # Lists inside blockquotes should be indented
MD033:        # Inline HTML should be allowed
  allowed_elements:
    - br
    - sub
    - sup
    - span
    - div
    - img
MD034: true   # Bare URL should be converted to link
MD035: true   # Horizontal rule style should be consistent
MD036: true   # Emphasis should not use spaces inside markers
MD037: true   # Spaces inside emphasis markers should be removed
MD038: true   # Spaces inside code span markers should be removed
MD039: true   # Spaces inside link text should be preserved
MD040: true   # Fenced code blocks should have a language specified
MD041: true   # First line should be top-level heading
MD042: true   # No empty URLs
MD043: true   # Headings should have consistent capitalization
MD044: true   # Code block content should match language
MD045: true   # No images without alt text
MD046: true   # Code block style should be consistent

# Rules to disable
MD006: false  # Considered too strict for some cases
MD021: false  # Header closing markers not required
MD047: false  # Trailing punctuation in code block language names